.TH XBANISH 1 2014-02-13 "John Hill" "xbanish Manual" 

.SH NAME
xbanish \- hide the X mouse cursor when you type

.SH SYNOPSIS
.B xbanish 
[\fI-d\fR]

.SH DESCRIPTION
.B xbanish
hides the mouse cursor when you start typing, and shows it again when the mouse
cursor moves or a mouse button is pressed.  This is similar to \fBxterm\fR(1)'s
\fBpointerMode\fR setting, but xbanish works globally in the X11 session.

.SH OPTIONS
.BR \-d
Print debugging messages to stdout

.SH AUTHORS
Joshua Stein
(jcs@jcs.com)

.SH SEE ALSO
\fBxfixes\fR(3)
