.Dd $Mdocdate: June 10 2015$
.Dt XBANISH 1
.Os
.Sh NAME
.Nm xbanish
.Nd hide the X11 mouse cursor when a key is pressed
.Sh SYNOPSIS
.Nm
.Op Fl d
.Op Fl i Ar modifier
.Sh DESCRIPTION
.Nm
hides the X11 mouse cursor when a key is pressed.
The cursor is shown again when it is moved or a mouse button is pressed.
This is similar to the
.Xr xterm 1
setting
.Ic pointerMode
but the effect is global in the X11 session.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl d
Print debugging messages to stdout.
.It Fl i Ar modifier
Ignore pressed key if
.Ar modifier
is used.
Modifiers are:
.Ic shift ,
.Ic lock
(CapsLock),
.Ic control ,
.Ic mod1
(Alt or Meta),
.Ic mod2
(NumLock),
.Ic mod3
(Hyper),
.Ic mod4
(Super, Windows, or Command), and
.Ic mod5
(ISO Level 3 Shift).
.El
.Sh SEE ALSO
.Xr XFixes 3
.Sh AUTHORS
.Nm
was written by
.An joshua stein Aq Mt jcs@jcs.org .
