.Dd $Mdocdate: March 13 2020$
.Dt XBANISH 1
.Os
.Sh NAME
.Nm xbanish
.Nd hide the X11 mouse cursor when a key is pressed
.Sh SYNOPSIS
.Nm
.Op Fl a
.Op Fl d
.Op Fl i Ar modifier
.Op Fl m Oo Ar w Oc Ns Ar nw|ne|sw|se|\(+-x\(+-y
.Op Fl t Ar seconds
.Op Fl s
.Sh DESCRIPTION
.Nm
hides the X11 mouse cursor when a key is pressed.
The cursor is shown again when it is moved or a mouse button is pressed.
This is similar to the
.Xr xterm 1
setting
.Ic pointerMode
but the effect is global in the X11 session.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl a
Always keep mouse cursor hidden while
.Nm
is running.
.It Fl d
Print debugging messages to stdout.
.It Fl i Ar modifier
Ignore pressed key if
.Ar modifier
is used.
Modifiers are:
.Ic shift ,
.Ic lock
(CapsLock),
.Ic control ,
.Ic mod1
(Alt or Meta),
.Ic mod2
(NumLock),
.Ic mod3
(Hyper),
.Ic mod4
(Super, Windows, or Command),
.Ic mod5
(ISO Level 3 Shift), and
.Ic all
.It Fl m Oo Ar w Oc Ns Ar nw|ne|sw|se|\(+-x\(+-y
When hiding the mouse cursor, move it to this corner of the screen
or current window, then move it back when showing the cursor.
Also accepts absolute positioning, for example `+50-100' will be
positioned 50 pixels from the left and 100 pixels from the bottom.
See GEOMETRY SPECIFICATIONS of X(7) for more info.
.It Fl t Ar seconds
Hide the mouse cursor after
.Ic seconds
have passed without mouse movement.
.It Fl s
Ignore scrolling events.
.El
.Sh SEE ALSO
.Xr XFixes 3
.Xr X 7
.Sh AUTHORS
.Nm
was written by
.An joshua stein Aq Mt jcs@jcs.org .
